const PRIMARY_COLOR = '#0d47a1';
const BUTTON = PRIMARY_COLOR;
const TAB_BAR_COLOR = PRIMARY_COLOR;
const BACKGROUND = '#fff';
const TEXT_FIELD = '#002171';
const BUTTON_TEXT = '#fff';
const ERROR_TEXT = '#ff0033';
const BORDER = '#5472d3';
const LINK = '#82b1ff';

export {
  BUTTON,
  BACKGROUND,
  TEXT_FIELD,
  BUTTON_TEXT,
  ERROR_TEXT,
  TAB_BAR_COLOR,
  BORDER,
  PRIMARY_COLOR,
  LINK,
};
